### ISSUE TITLE
Please, consider documenting how to make the MATH support

### ISSUE THREAD

**Issue by rbrito** [khaledhosny/xits-math#20]
Hi, Khaled.

Your work here is impressive and I see that you have distilled a lot of knowledge with the creation of the XITS fonts.

As a by-product of this, could you create a document (well, anything at all is better than no document) on how one would go adding support for mathematics to a font? Ideally, this could be converted, as much as possible, in a set of scripts, with the fine-tuning being left for humans?

I would be one of the first persons to apply your expertise to some other fonts as an experiment.

Thanks so much for the work you've been doing.

**Comment by khaledhosny** [comment]
Five years later, I don’t think I’m going to do this. Hopefully there are enough documentation by now.
