### ISSUE TITLE
Product signs cut off when converting to PDF

### ISSUE THREAD

**Issue by AzrgExplorers** [khaledhosny/xits-math#41]
I'm using XITS with Word 2013. If a document contains product signs (from the Large Operator menu in Equation tools), the product signs are mangled when the document is converted to PDF. For example, these equations in Word:
![productfailword](https://cloud.githubusercontent.com/assets/5505409/5513391/2c3b1c00-87af-11e4-98a0-be90be115039.PNG)
are rendered like this in the PDF:
![productfailpdf](https://cloud.githubusercontent.com/assets/5505409/5513396/4730ec60-87af-11e4-89bd-75cf8093b1a7.PNG)
(The first equation is a numbered equation in a table, while the second is a bare equation on its own line. The equations are in 12-point font, though changing the font size doesn't seem to affect the results.)

This doesn't happen if I use Cambria Math, so it appears to be a XITS issue, not a Word issue. Fortunately, summation signs seem to work fine.

**Comment by khaledhosny** [comment]
Is this still an issue?

**Comment by pawaa** [comment]
I'm using Microsoft Word 2016 with XITS 1.108 and I'm havig the same problems with the product and integral sign. I'm algo also using export to pdf feature in Word.

**Comment by khaledhosny** [comment]
I think Word’s built-in PDF export feature is just buggy. It does not support embedding CFF fonts (like XITS) and instead embeds the glyphs as raster images, and whatever code doing that rasterisation seems to be buggy. As such I suggest using any of the other available PDF painters that seem to be doing a better job.

**Comment by pawaa** [comment]
I belive it is the built-in PDF export feature of Word. I printed the document to PDF instead of exporting it and everything looked good.

**Comment by khaledhosny** [comment]
OK, closing then. Thanks.

**Comment by Dom303** [comment]
Word 2013-2016 does not support font embedding using Open Type Fonts (.otf), it only supports it using TrueType Fonts (.ttf). 
To fix the problem, all you have to do is follow this simple steps:
1. Convert the font to .ttf using a converter. I used this website [https://onlinefontconverter.com/](url).
2. Install the converted files. You will be prompted that the font is already install, choose "yes" to replace the old installation.
3. Enjoy :)
4. To help you, I attached a .zip file that contains the XTIS font if .ttf format.
[XITS-TTF.zip](https://github.com/khaledhosny/xits-math/files/247064/XITS-TTF.zip)
