### ISSUE TITLE
Vertical line causes wrong subscript position

### ISSUE THREAD

**Issue by schlasim** [khaledhosny/xits-math#43]
When inserting a vertical line as right delimiter of a fraction in Word 2013, the subscript of xits-math (xits-1.106) is set too high (see attachment).
[bug-in-xits.pdf](https://github.com/khaledhosny/xits-math/files/84044/bug-in-xits.pdf)

**Comment by khaledhosny** [comment]
I don’t have a MS Office to test right now, but can you check if the last commit fixes it?

**Comment by khaledhosny** [comment]
I didn’t mean to close this yet.

**Comment by schlasim** [comment]
Sorry for my late answer. I hope I can check it soon.

**Comment by schlasim** [comment]
It seems fixed.
[bug-in-xits-print.pdf](https://github.com/khaledhosny/xits-math/files/96502/bug-in-xits-print.pdf)
