### ISSUE TITLE
Some symbols are missing when exporting as PDF using Word 2013

### ISSUE THREAD

**Issue by schlasim** [khaledhosny/xits-math#44]
If I use the Word 2013 export as PDF feature, some symbols are missing (see attachments). If I create a PDF using the Microsoft print to PDF function, everything looks fine.
[bug-in-xits.pdf](https://github.com/khaledhosny/xits-math/files/96506/bug-in-xits.pdf)
[bug-in-xits-print.pdf](https://github.com/khaledhosny/xits-math/files/96505/bug-in-xits-print.pdf)

**Comment by khaledhosny** [comment]
Word’s PDF export does not seem to support CFF fonts at all, it just rasterises them, so I just assume it is a bug in this rasterisation. I think it is not a very good idea to use it with CFF fonts anyway.

**Comment by schlasim** [comment]
I see. We could close this issue, I guess.

**Comment by Dom303** [comment]
Check my answer at this post :)
All you have to do, is convert the ".otf" font to a ".ttf".
https://github.com/khaledhosny/xits-math/issues/41
