### ISSUE TITLE
Arabic Mathematical Alphabetic Symbols, part 2

### ISSUE THREAD

**Issue by fred-wang** [khaledhosny/xits-math#45]
I'm just opening this follow-up of #36 for the record. See https://github.com/khaledhosny/xits-math/issues/36#issuecomment-30652701

[ ] redesign the glyphs
[ ] Add U+1EEF0 and U+1EEF1
[ ] Make U+1EEF0 and U+1EEF1 stretchable

**Comment by khaledhosny** [comment]
This is more or less done with c109334150dd15306f4fb65692ba169dbb62c244. I think I’m happy with the current state of the design (though it is not exactly what I had in mind previously).
