### ISSUE TITLE
Spacing of displayed integral limits in luatex is poor

### ISSUE THREAD

**Issue by juliangilbey** [khaledhosny/xits-math#47]
Please see [this luatex bug report](http://tracker.luatex.org/view.php?id=982) where I provide examples of how lualatex produces very poor limits spacing when typesetting integrals in display style.

Hans suggests that it is a lack of appropriate OpenType kerning information; I don't understand the details here, but I have noticed that XeLaTeX is able to typeset the integral without difficulty.

I don't know whether this is easy to fix or not.

Thanks!

**Comment by khaledhosny** [comment]
It is a LuaTeX bug, the font works fine in XeTeX and MS Office.

**Comment by juliangilbey** [comment]
OK, thanks, I've reported it back to LuaTeX.
