### ISSUE TITLE
Making subscript and superscript characters combining together

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/xits-math#48]
This feature would making these chatacters useful to produce certain case as *x*²ⁿ₀, see the behavior in Libertinus Serif.

**Comment by khaledhosny** [comment]
Please explain more what is being requested e.g. with screenshots.

**Comment by KrasnayaPloshchad** [comment]
![My screenshot](https://ooo.0o0.ooo/2017/05/18/591d0dd20bc21.png)

**Comment by khaledhosny** [comment]
XITS behavior is correct and Libertinus is wrong. These are spacing characters and should not be combined this way. Furthermore the Unicode superscripts and subscripts are not encoded for mathematics and using them for that is wrong, if you want math superscripts and subscripts use XITS Math with a proper math typesetting engine.

**Comment by khaledhosny** [comment]
Not to mention that `₀` is not even supported by XITS, what you are getting is a fallback character.

**Comment by KrasnayaPloshchad** [comment]
I’m misoberved, sorry. BTW I found inserting ZWNJ can prevent Unicode superscripts and subscripts combined together in Libertinus.
