### ISSUE TITLE
Is this obsolete?

### ISSUE THREAD

**Issue by behdad** [khaledhosny/xits-math#49]
Khaled,

Given that STIX 2 has a math font, what's the status of this project.  Can you please clarify?

**Comment by fred-wang** [comment]
@behdad STIX 2 does not have features needed by https://www.w3.org/TR/arabic-math/ (like arabic mathvariants, mirrored glyphs etc).

**Comment by khaledhosny** [comment]
In addition to Arabic math, like @fred-wang mentioned, I have also seen few reports of XITS Math performing better with TeX engines compared to STIX Two Math, also few people want the old, more Times-like design for whatever reason. That being said the font is basically in maintenance mode right now.

**Comment by KrasnayaPloshchad** [comment]
But this font lakes some font features founded at STIX Two: small caps, sub/superscripts...
